/*
* (C) Copyright 2009-2013 Manaty SARL (http://manaty.net/) and contributors.
*
* Licensed under the GNU Public Licence, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.gnu.org/licenses/gpl-2.0.txt
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.02 at 02:29:16 PM WET 
//

package org.meveo.model.jaxb.customer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}desCustomer"/>
 *         &lt;element ref="{}customerAccounts"/>
 *       &lt;/sequence>
 *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="customerCategory" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="customerBrand" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "desCustomer", "customerAccounts" })
@XmlRootElement(name = "customer")
public class Customer {

    protected String desCustomer;
    protected CustomerAccounts customerAccounts;
    @XmlAttribute(name = "code")
    protected String code;
    @XmlAttribute(name = "customerCategory")
    protected String customerCategory;
    @XmlAttribute(name = "customerBrand")
    protected String customerBrand;

    /**
     * Gets the value of the desCustomer property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDesCustomer() {
        return desCustomer;
    }

    /**
     * Sets the value of the desCustomer property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDesCustomer(String value) {
        this.desCustomer = value;
    }

    /**
     * Gets the value of the customerAccounts property.
     * 
     * @return possible object is {@link CustomerAccounts }
     * 
     */
    public CustomerAccounts getCustomerAccounts() {
        return customerAccounts;
    }

    /**
     * Sets the value of the customerAccounts property.
     * 
     * @param value
     *            allowed object is {@link CustomerAccounts }
     * 
     */
    public void setCustomerAccounts(CustomerAccounts value) {
        this.customerAccounts = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the customerCategory property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomerCategory() {
        return customerCategory;
    }

    /**
     * Sets the value of the customerCategory property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomerCategory(String value) {
        this.customerCategory = value;
    }

    /**
     * Gets the value of the customerBrand property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomerBrand() {
        return customerBrand;
    }

    /**
     * Sets the value of the customerBrand property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomerBrand(String value) {
        this.customerBrand = value;
    }

}
