DROP TABLE ADM_USER_LOG IF EXISTS;
DROP SEQUENCE USER_LOG_SEQ IF EXISTS;
CREATE SEQUENCE USER_LOG_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE ADM_USER_LOG( ID INTEGER NOT NULL,USER_NAME VARCHAR(255) NOT NULL, USER_ID INTEGER NOT NULL, DATE_EXECUTED DATE,ACTION VARCHAR(255), URL VARCHAR(255) NOT NULL, OBJECT_ID VARCHAR(255), PRIMARY KEY (ID));
